POST http://127.0.0.1:8000/partner/login
Content-Type: application/json

{"username": "Testando123", "password": "123.456-03"}

###

POST http://127.0.0.1:8000/partner/singup
Content-Type: application/json

{"username": "testando_email", "password": "4002-8922.02", "email": "testaemail@gmail.com"}


###

GET http://127.0.0.1:8000/partner/test_token
Content-Type: application/json
Authorization: Token 1959479da7c30914e038803b3b49be70b68f3d76

{}