# Generated by Django 4.2.5 on 2023-11-21 19:43

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('deadline_in_hours', models.DurationField()),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_sale', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('birth_date', models.DateField()),
                ('personal_id_number', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf')),
                ('phone_number', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
