# Generated by Django 4.2.5 on 2023-11-23 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_internaltest_alias_internaltest_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_lab_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
